name: Deploy to Render

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run tests
      env:
        SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
        SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        APP_JWTSECRET: ${{ secrets.APP_JWTSECRET }}
        DEVQUOTE_CORS_ALLOWED_ORIGINS: ${{ secrets.DEVQUOTE_CORS_ALLOWED_ORIGINS }}
        PORT: ${{ secrets.PORT }}
        # Email configuration - Required for Spring context loading
        DEVQUOTE_EMAIL_ENABLED: ${{ secrets.DEVQUOTE_EMAIL_ENABLED }}
        DEVQUOTE_EMAIL_FROM: ${{ secrets.DEVQUOTE_EMAIL_FROM }}
        DEVQUOTE_EMAIL_FINANCE: ${{ secrets.DEVQUOTE_EMAIL_FINANCE }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        # AWS S3 configuration - Required for file upload functionality
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      run: mvn clean test
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          wesleyeduardodev/devquote-backend:latest
          wesleyeduardodev/devquote-backend:${{ github.sha }}
    
    - name: Deploy to Render
      run: |
        echo "🚀 Triggering Render deployment..."
        response=$(curl -s -w "%{http_code}" -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}")
        http_code=$(echo "$response" | tail -c 4)
        
        if [ "$http_code" = "200" ] || [ "$http_code" = "201" ]; then
          echo "✅ Deploy triggered successfully! HTTP Code: $http_code"
        else
          echo "❌ Deploy failed! HTTP Code: $http_code"
          exit 1
        fi
    
    - name: Notify completion
      run: |
        echo "🎉 Pipeline completed successfully!"
        echo "📦 Docker image: wesleyeduardodev/devquote-backend:${{ github.sha }}"
        echo "🔄 Render deployment triggered"